### PR TITLE
adds pep508 url to setup.py 'install_requires'

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by gnott** [comment]
@lsh-0 do you have any comments about this PR?

**Comment by lsh-0** [comment]
I'm not sure what your intent is here, all of those packages are on Pypi. You and I spent some effort getting automatic releases to Pypi happening. Why point them at the `develop` branch of a git repo?

from: https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/

> [...] used to specify what a project minimally needs to run correctly. When the project is installed by [pip](https://packaging.python.org/en/latest/key_projects/#pip), this is the specification that is used to install its dependencies.

and from here: https://peps.python.org/pep-0440/#direct-references

> Direct references are intended as a tool for software integrators rather than publishers.
> 
> Depending on the use case, some appropriate targets for a direct URL reference may be an sdist or a wheel binary archive. The exact URLs and targets supported will be tool dependent.

Can you explain a bit more what you're trying to achieve here?

If anything I would recommend constraining the versions `jats-generator` depends on:

```python
    install_requires=[
        "elifetools>=1.0.0",
        "elifearticle>=1.0.0",
        "ejpcsvparser>=1.0.0",
        "GitPython",
        "configparser"
    ],
```

**Comment by gnott** [comment]
I was asking primarily because I think you opened this PR, and I wasn't sure of its intent. Seeing as it is old, it may be out-of-date.

None of the Python libraries I'm maintaining specify exact versions of requirements yet, and it may be possible in the future, I like the idea, however there's no rush to do it unless you feel otherwise.

**Comment by lsh-0** [comment]
> I was asking primarily because I think you opened this PR, and I wasn't sure of its intent. Seeing as it is old, it may be out-of-date.

I did? I did! Weird. I think this may have been one of many PRs I opened prior to us doing Pypi releases.

> None of the Python libraries I'm maintaining specify exact versions of requirements yet, and it may be possible in the future, I like the idea, however there's no rush to do it unless you feel otherwise.

At your own pace. If the need arises we can look at constraining versions then.

For now I'm closing this PR. Sorry for the confusion, I thought you were experimenting with something new.

**Comment by gnott** [comment]
My fault for not describing why I pinged you on it, all good, thanks for your input!

**Pull request closed without merging**
